Progetto 1: Pulizia e Standardizzazione di Dati Geografici 🗺️
Obiettivo: Importare un dataset contenente informazioni 
geografiche disordinate e prepararlo per un'analisi o 
una visualizzazione, focalizzandosi sulla pulizia e 
l'uniformità dei formati.

Fasi Procedurali Suggerite
Caricamento dei Dati:

Carica un file CSV (o un altro formato a tua scelta, 
ad esempio un dataset su città, stati o codici postali che puoi 
trovare online) in un DataFrame pandas.

Ispezione Iniziale:

Verifica i tipi di dati (.dtypes), il numero di valori mancanti 
(.isnull().sum()) e le prime righe (.head()).

Gestione dei Valori Mancanti:

Identifica le colonne con valori mancanti 
(ad es., latitudine o longitudine).

Decidi se eliminare le righe che contengono 
troppi NaN in colonne critiche o se imputare i valori mancanti 
(ad es., con la moda per i nomi delle regioni o lo zero per le 
popolazioni sconosciute).

Pulizia delle Stringhe:

Nella colonna dei nomi delle città/regioni:

Rimuovi gli spazi bianchi iniziali e finali (.str.strip()).

Converti tutti i nomi in minuscolo 
(.str.lower()) o in maiuscolo per uniformità.

Rimuovi caratteri speciali, punteggiatura non necessaria 
o numeri all'interno dei nomi.

Standardizzazione dei Formati Numerici:

Assicurati che le colonne come Popolazione o Area siano 
trattate come tipi numerici.

Se ci sono separatori di migliaia non standard 
(ad es., punti al posto delle virgole o viceversa), 
rimuovili o sostituiscili prima della conversione a 
numerico (pd.to_numeric()).

Creazione di Nuove Caratteristiche:

Crea una nuova colonna che categorizzi le città in 
base alla loro popolazione 
(ad es., 'Piccola', 'Media', 'Grande') 
utilizzando pd.cut() o np.select.

In [1]:
import pandas as pd 

df = pd.read_csv('GeoInfo_Cittòvalle.csv')

In [2]:
df

,ID,Quartiere,Latitudine,Longitudine,Popolazione,Altitudine (m),Superficie (km2),Tipo Zona,Note
0,1,Centro Storico,45.4628,9.107,18230,135,2.3,residenziale,centro turisticO
1,2,Borgo Nord,45.467,9.109,12000,142,3.1,misto,zona industriale vicino al fiume
2,3,zona sud est,45.456,9.112,-,128,4.0,residenziale,presenza di scuole
3,4,Colline Verdi,nd,9.118,8300,200,5.5,rurale,altitudine da verificare
4,5,Industriale,45.470,9.115,34000,130,n/d,industriale,Dati da confermare
5,6,centro storico,45.4628,9.107,18100,135,2.3,Residenziale,duplicato (vedi ID 1)
6,7,Parco Est,45.459,-,5900,110,3.4,verde,coordinate incomplete
7,8,Borgo Nord,45.467,9.109,12200,142,3.1,MISTO,possibile duplicato (ID 2)
8,9,Zona sud-est,45.4559,9.1121,n.d.,127,4.0,residenziale,varianti nel nome
9,10,NaN,45.46,9.11,10100,129,3.0,sconosciuto,nome mancante
10,11,ValleOvest,45.4632,9.103,9200,121,2.9,Residenziale,nuovo quartiere
11,12,Borgo Nord,45.467,9.109,12150,142,3.1,Misto,terzo duplicato
12,13,Campagna Sud,45.451,9.100,3400,NaN,6.2,rurale,altitudine mancante
13,14,Parco est,45.459,-,NaN,110,3.4,Verde,coordinate mancanti
14,15,Zona Expo,45.471,9.120,18400,138,3.8,commerciale,zona fieristica
15,16,ZonaExpo,45.471,9.120,18300,138,3.8,Commerciale,simile a ID 15
16,17,Quartiere Luna,45.468,9.116,0,145,3.0,Residenziale,Popolazione forse errata
17,18,NaN,NaN,NaN,9800,133,2.5,sconosciuto,dati completamente mancanti
18,19,Colline verdi,N.D,9.118,8250,202,5.5,rurale,maiuscole incoerenti
19,20,Nuova zona,45.472,9.122,15000,139,4.2,Residenziale,-
20,21,Vecchia zona,45.440,9.099,-200,125,3.3,Residenziale,valore popolazione negativo
21,22,Centro Antico,45.4628,9.107,17900,135,2.3,residenziale,possibile duplicato di centro
22,23,ParcoEst,45.459,9.114,6100,110,3.4,Verde,varianti su Parco Est
23,24,Zona Sud,45.453,9.110,n.d.,127,4.1,residenziale,popolazione mancante
24,25,Montealto,45.480,9.140,4300,260,6.5,rurale,zona collinare
25,26,zona expo,45.471,9.120,18500,138,3.8,commerciale,altra variante
26,27,Villaggio Lago,45.475,9.099,7200,-,3.9,residenziale,altitudine assente
27,28,Quartiere Luna,45.468,9.116,100,145,3.0,residenziale,duplicato con variazione pop.
28,29,Campagna Sud,45.451,9.100,3600,N.D.,6.2,Rurale,duplicato con nome identico
29,30,ZonaEst,45.460,9.111,10500,132,3.6,residenziale,nome scritto unito

In [3]:
df.head(5)

,ID,Quartiere,Latitudine,Longitudine,Popolazione,Altitudine (m),Superficie (km2),Tipo Zona,Note
0,1,Centro Storico,45.4628,9.107,18230,135,2.3,residenziale,centro turisticO
1,2,Borgo Nord,45.467,9.109,12000,142,3.1,misto,zona industriale vicino al fiume
2,3,zona sud est,45.456,9.112,-,128,4.0,residenziale,presenza di scuole
3,4,Colline Verdi,nd,9.118,8300,200,5.5,rurale,altitudine da verificare
4,5,Industriale,45.470,9.115,34000,130,n/d,industriale,Dati da confermare

In [4]:
df.dtypes

ID                   int64
Quartiere           object
Latitudine          object
Longitudine         object
Popolazione         object
Altitudine (m)      object
Superficie (km2)    object
Tipo Zona           object
Note                object
dtype: object

In [5]:
df.isnull().sum()

ID                  0
Quartiere           2
Latitudine          1
Longitudine         1
Popolazione         1
Altitudine (m)      1
Superficie (km2)    0
Tipo Zona           0
Note                0
dtype: int64

In [6]:
new_df = df.dropna()
new_df

,ID,Quartiere,Latitudine,Longitudine,Popolazione,Altitudine (m),Superficie (km2),Tipo Zona,Note
0,1,Centro Storico,45.4628,9.107,18230,135,2.3,residenziale,centro turisticO
1,2,Borgo Nord,45.467,9.109,12000,142,3.1,misto,zona industriale vicino al fiume
2,3,zona sud est,45.456,9.112,-,128,4.0,residenziale,presenza di scuole
3,4,Colline Verdi,nd,9.118,8300,200,5.5,rurale,altitudine da verificare
4,5,Industriale,45.470,9.115,34000,130,n/d,industriale,Dati da confermare
5,6,centro storico,45.4628,9.107,18100,135,2.3,Residenziale,duplicato (vedi ID 1)
6,7,Parco Est,45.459,-,5900,110,3.4,verde,coordinate incomplete
7,8,Borgo Nord,45.467,9.109,12200,142,3.1,MISTO,possibile duplicato (ID 2)
8,9,Zona sud-est,45.4559,9.1121,n.d.,127,4.0,residenziale,varianti nel nome
10,11,ValleOvest,45.4632,9.103,9200,121,2.9,Residenziale,nuovo quartiere
11,12,Borgo Nord,45.467,9.109,12150,142,3.1,Misto,terzo duplicato
14,15,Zona Expo,45.471,9.120,18400,138,3.8,commerciale,zona fieristica
15,16,ZonaExpo,45.471,9.120,18300,138,3.8,Commerciale,simile a ID 15
16,17,Quartiere Luna,45.468,9.116,0,145,3.0,Residenziale,Popolazione forse errata
18,19,Colline verdi,N.D,9.118,8250,202,5.5,rurale,maiuscole incoerenti
19,20,Nuova zona,45.472,9.122,15000,139,4.2,Residenziale,-
20,21,Vecchia zona,45.440,9.099,-200,125,3.3,Residenziale,valore popolazione negativo
21,22,Centro Antico,45.4628,9.107,17900,135,2.3,residenziale,possibile duplicato di centro
22,23,ParcoEst,45.459,9.114,6100,110,3.4,Verde,varianti su Parco Est
23,24,Zona Sud,45.453,9.110,n.d.,127,4.1,residenziale,popolazione mancante
24,25,Montealto,45.480,9.140,4300,260,6.5,rurale,zona collinare
25,26,zona expo,45.471,9.120,18500,138,3.8,commerciale,altra variante
26,27,Villaggio Lago,45.475,9.099,7200,-,3.9,residenziale,altitudine assente
27,28,Quartiere Luna,45.468,9.116,100,145,3.0,residenziale,duplicato con variazione pop.
28,29,Campagna Sud,45.451,9.100,3600,N.D.,6.2,Rurale,duplicato con nome identico
29,30,ZonaEst,45.460,9.111,10500,132,3.6,residenziale,nome scritto unito

In [7]:
import numpy as np

In [8]:
new_df['Latitudine'] = new_df['Latitudine'].replace(['nd', 'ND', 'N.D', 'N.D.'], np.nan)
new_df['Latitudine'] = pd.to_numeric(new_df['Latitudine'], errors='coerce')
new_df['Latitudine'].fillna(130, inplace = True)
new_df['Latitudine']

C:\Users\Roman\AppData\Local\Temp\ipykernel_3212\3022349746.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['Latitudine'] = new_df['Latitudine'].replace(['nd', 'ND', 'N.D', 'N.D.'], np.nan)
C:\Users\Roman\AppData\Local\Temp\ipykernel_3212\3022349746.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['Latitudine'] = pd.to_numeric(new_df['Latitudine'], errors='coerce')
C:\Users\Roman\AppData\Local\Temp\ipykernel_3212\3022349746.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  new_df['Latitudine'].fillna(130, inplace = True)
C:\Users\Roman\AppData\Local\Temp\ipykernel_3212\3022349746.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['Latitudine'].fillna(130, inplace = True)

0      45.4628
1      45.4670
2      45.4560
3     130.0000
4      45.4700
5      45.4628
6      45.4590
7      45.4670
8      45.4559
10     45.4632
11     45.4670
14     45.4710
15     45.4710
16     45.4680
18    130.0000
19     45.4720
20     45.4400
21     45.4628
22     45.4590
23     45.4530
24     45.4800
25     45.4710
26     45.4750
27     45.4680
28     45.4510
29     45.4600
Name: Latitudine, dtype: float64

In [9]:
new_df['Longitudine']

0      9.107
1      9.109
2      9.112
3      9.118
4      9.115
5      9.107
6          -
7      9.109
8     9.1121
10     9.103
11     9.109
14     9.120
15     9.120
16     9.116
18     9.118
19     9.122
20     9.099
21     9.107
22     9.114
23     9.110
24     9.140
25     9.120
26     9.099
27     9.116
28     9.100
29     9.111
Name: Longitudine, dtype: object

In [10]:
new_df['Longitudine'] = new_df['Longitudine'].replace('-', np.nan)
new_df['Longitudine'] = pd.to_numeric(new_df['Longitudine'], errors='coerce')
new_df['Longitudine'].fillna(130, inplace = True)
new_df['Longitudine']

C:\Users\Roman\AppData\Local\Temp\ipykernel_3212\297086289.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['Longitudine'] = new_df['Longitudine'].replace('-', np.nan)
C:\Users\Roman\AppData\Local\Temp\ipykernel_3212\297086289.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['Longitudine'] = pd.to_numeric(new_df['Longitudine'], errors='coerce')
C:\Users\Roman\AppData\Local\Temp\ipykernel_3212\297086289.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  new_df['Longitudine'].fillna(130, inplace = True)
C:\Users\Roman\AppData\Local\Temp\ipykernel_3212\297086289.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['Longitudine'].fillna(130, inplace = True)

0       9.1070
1       9.1090
2       9.1120
3       9.1180
4       9.1150
5       9.1070
6     130.0000
7       9.1090
8       9.1121
10      9.1030
11      9.1090
14      9.1200
15      9.1200
16      9.1160
18      9.1180
19      9.1220
20      9.0990
21      9.1070
22      9.1140
23      9.1100
24      9.1400
25      9.1200
26      9.0990
27      9.1160
28      9.1000
29      9.1110
Name: Longitudine, dtype: float64

In [11]:
new_df['Popolazione']

0     18230
1     12000
2         -
3      8300
4     34000
5     18100
6      5900
7     12200
8      n.d.
10     9200
11    12150
14    18400
15    18300
16        0
18     8250
19    15000
20     -200
21    17900
22     6100
23     n.d.
24     4300
25    18500
26     7200
27      100
28     3600
29    10500
Name: Popolazione, dtype: object

In [12]:
new_df['Popolazione'] = new_df['Popolazione'].replace(['nd', '-', 0, -200, 'N.D.'], np.nan)
new_df['Popolazione'] = pd.to_numeric(new_df['Popolazione'], errors='coerce')
new_df['Popolazione'].fillna(130, inplace = True)
new_df['Popolazione']

C:\Users\Roman\AppData\Local\Temp\ipykernel_3212\2095162339.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['Popolazione'] = new_df['Popolazione'].replace(['nd', '-', 0, -200, 'N.D.'], np.nan)
C:\Users\Roman\AppData\Local\Temp\ipykernel_3212\2095162339.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['Popolazione'] = pd.to_numeric(new_df['Popolazione'], errors='coerce')
C:\Users\Roman\AppData\Local\Temp\ipykernel_3212\2095162339.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  new_df['Popolazione'].fillna(130, inplace = True)
C:\Users\Roman\AppData\Local\Temp\ipykernel_3212\2095162339.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['Popolazione'].fillna(130, inplace = True)

0     18230.0
1     12000.0
2       130.0
3      8300.0
4     34000.0
5     18100.0
6      5900.0
7     12200.0
8       130.0
10     9200.0
11    12150.0
14    18400.0
15    18300.0
16        0.0
18     8250.0
19    15000.0
20     -200.0
21    17900.0
22     6100.0
23      130.0
24     4300.0
25    18500.0
26     7200.0
27      100.0
28     3600.0
29    10500.0
Name: Popolazione, dtype: float64

In [13]:
new_df['Altitudine (m)']

0      135
1      142
2      128
3      200
4      130
5      135
6      110
7      142
8      127
10     121
11     142
14     138
15     138
16     145
18     202
19     139
20     125
21     135
22     110
23     127
24     260
25     138
26       -
27     145
28    N.D.
29     132
Name: Altitudine (m), dtype: object

In [14]:
new_df['Altitudine (m)'] = new_df['Altitudine (m)'].replace(['-', 'N.D.'], np.nan)
new_df['Altitudine (m)'] = pd.to_numeric(new_df['Altitudine (m)'], errors='coerce')
new_df['Altitudine (m)'].fillna(130, inplace = True)
new_df['Altitudine (m)']

C:\Users\Roman\AppData\Local\Temp\ipykernel_3212\1876019150.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['Altitudine (m)'] = new_df['Altitudine (m)'].replace(['-', 'N.D.'], np.nan)
C:\Users\Roman\AppData\Local\Temp\ipykernel_3212\1876019150.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['Altitudine (m)'] = pd.to_numeric(new_df['Altitudine (m)'], errors='coerce')
C:\Users\Roman\AppData\Local\Temp\ipykernel_3212\1876019150.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  new_df['Altitudine (m)'].fillna(130, inplace = True)
C:\Users\Roman\AppData\Local\Temp\ipykernel_3212\1876019150.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['Altitudine (m)'].fillna(130, inplace = True)

0     135.0
1     142.0
2     128.0
3     200.0
4     130.0
5     135.0
6     110.0
7     142.0
8     127.0
10    121.0
11    142.0
14    138.0
15    138.0
16    145.0
18    202.0
19    139.0
20    125.0
21    135.0
22    110.0
23    127.0
24    260.0
25    138.0
26    130.0
27    145.0
28    130.0
29    132.0
Name: Altitudine (m), dtype: float64

In [15]:
new_df['Superficie (km2)']

0     2.3
1     3.1
2     4.0
3     5.5
4     n/d
5     2.3
6     3.4
7     3.1
8     4.0
10    2.9
11    3.1
14    3.8
15    3.8
16    3.0
18    5.5
19    4.2
20    3.3
21    2.3
22    3.4
23    4.1
24    6.5
25    3.8
26    3.9
27    3.0
28    6.2
29    3.6
Name: Superficie (km2), dtype: object

In [16]:
new_df['Superficie (km2)'] = new_df['Superficie (km2)'].replace('n/d', np.nan)
new_df['Superficie (km2)'] = pd.to_numeric(new_df['Superficie (km2)'], errors='coerce')
new_df['Superficie (km2)'].fillna(130, inplace = True)
new_df['Superficie (km2)']

C:\Users\Roman\AppData\Local\Temp\ipykernel_3212\3170429495.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['Superficie (km2)'] = new_df['Superficie (km2)'].replace('n/d', np.nan)
C:\Users\Roman\AppData\Local\Temp\ipykernel_3212\3170429495.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['Superficie (km2)'] = pd.to_numeric(new_df['Superficie (km2)'], errors='coerce')
C:\Users\Roman\AppData\Local\Temp\ipykernel_3212\3170429495.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  new_df['Superficie (km2)'].fillna(130, inplace = True)
C:\Users\Roman\AppData\Local\Temp\ipykernel_3212\3170429495.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['Superficie (km2)'].fillna(130, inplace = True)

0       2.3
1       3.1
2       4.0
3       5.5
4     130.0
5       2.3
6       3.4
7       3.1
8       4.0
10      2.9
11      3.1
14      3.8
15      3.8
16      3.0
18      5.5
19      4.2
20      3.3
21      2.3
22      3.4
23      4.1
24      6.5
25      3.8
26      3.9
27      3.0
28      6.2
29      3.6
Name: Superficie (km2), dtype: float64

In [17]:
new_df.isnull().sum()

ID                  0
Quartiere           0
Latitudine          0
Longitudine         0
Popolazione         0
Altitudine (m)      0
Superficie (km2)    0
Tipo Zona           0
Note                0
dtype: int64

In [18]:
new_df

,ID,Quartiere,Latitudine,Longitudine,Popolazione,Altitudine (m),Superficie (km2),Tipo Zona,Note
0,1,Centro Storico,45.4628,9.1070,18230.0,135.0,2.3,residenziale,centro turisticO
1,2,Borgo Nord,45.4670,9.1090,12000.0,142.0,3.1,misto,zona industriale vicino al fiume
2,3,zona sud est,45.4560,9.1120,130.0,128.0,4.0,residenziale,presenza di scuole
3,4,Colline Verdi,130.0000,9.1180,8300.0,200.0,5.5,rurale,altitudine da verificare
4,5,Industriale,45.4700,9.1150,34000.0,130.0,130.0,industriale,Dati da confermare
5,6,centro storico,45.4628,9.1070,18100.0,135.0,2.3,Residenziale,duplicato (vedi ID 1)
6,7,Parco Est,45.4590,130.0000,5900.0,110.0,3.4,verde,coordinate incomplete
7,8,Borgo Nord,45.4670,9.1090,12200.0,142.0,3.1,MISTO,possibile duplicato (ID 2)
8,9,Zona sud-est,45.4559,9.1121,130.0,127.0,4.0,residenziale,varianti nel nome
10,11,ValleOvest,45.4632,9.1030,9200.0,121.0,2.9,Residenziale,nuovo quartiere
11,12,Borgo Nord,45.4670,9.1090,12150.0,142.0,3.1,Misto,terzo duplicato
14,15,Zona Expo,45.4710,9.1200,18400.0,138.0,3.8,commerciale,zona fieristica
15,16,ZonaExpo,45.4710,9.1200,18300.0,138.0,3.8,Commerciale,simile a ID 15
16,17,Quartiere Luna,45.4680,9.1160,0.0,145.0,3.0,Residenziale,Popolazione forse errata
18,19,Colline verdi,130.0000,9.1180,8250.0,202.0,5.5,rurale,maiuscole incoerenti
19,20,Nuova zona,45.4720,9.1220,15000.0,139.0,4.2,Residenziale,-
20,21,Vecchia zona,45.4400,9.0990,-200.0,125.0,3.3,Residenziale,valore popolazione negativo
21,22,Centro Antico,45.4628,9.1070,17900.0,135.0,2.3,residenziale,possibile duplicato di centro
22,23,ParcoEst,45.4590,9.1140,6100.0,110.0,3.4,Verde,varianti su Parco Est
23,24,Zona Sud,45.4530,9.1100,130.0,127.0,4.1,residenziale,popolazione mancante
24,25,Montealto,45.4800,9.1400,4300.0,260.0,6.5,rurale,zona collinare
25,26,zona expo,45.4710,9.1200,18500.0,138.0,3.8,commerciale,altra variante
26,27,Villaggio Lago,45.4750,9.0990,7200.0,130.0,3.9,residenziale,altitudine assente
27,28,Quartiere Luna,45.4680,9.1160,100.0,145.0,3.0,residenziale,duplicato con variazione pop.
28,29,Campagna Sud,45.4510,9.1000,3600.0,130.0,6.2,Rurale,duplicato con nome identico
29,30,ZonaEst,45.4600,9.1110,10500.0,132.0,3.6,residenziale,nome scritto unito

In [19]:
new_df[new_df.duplicated('Quartiere', keep=False)]

,ID,Quartiere,Latitudine,Longitudine,Popolazione,Altitudine (m),Superficie (km2),Tipo Zona,Note
1,2,Borgo Nord,45.467,9.109,12000.0,142.0,3.1,misto,zona industriale vicino al fiume
7,8,Borgo Nord,45.467,9.109,12200.0,142.0,3.1,MISTO,possibile duplicato (ID 2)
11,12,Borgo Nord,45.467,9.109,12150.0,142.0,3.1,Misto,terzo duplicato
16,17,Quartiere Luna,45.468,9.116,0.0,145.0,3.0,Residenziale,Popolazione forse errata
27,28,Quartiere Luna,45.468,9.116,100.0,145.0,3.0,residenziale,duplicato con variazione pop.

In [20]:
new_df.loc[new_df['ID'] == 8]

,ID,Quartiere,Latitudine,Longitudine,Popolazione,Altitudine (m),Superficie (km2),Tipo Zona,Note
7,8,Borgo Nord,45.467,9.109,12200.0,142.0,3.1,MISTO,possibile duplicato (ID 2)

In [21]:
new_df.loc[new_df['ID'] == 8, 'Quartiere'] = 'borgo settentrionale'
new_df.loc[new_df['ID'] == 8]

,ID,Quartiere,Latitudine,Longitudine,Popolazione,Altitudine (m),Superficie (km2),Tipo Zona,Note
7,8,borgo settentrionale,45.467,9.109,12200.0,142.0,3.1,MISTO,possibile duplicato (ID 2)

In [22]:
new_df.loc[new_df['ID'] == 12, 'Quartiere'] = 'Villa Aurora'
new_df.loc[new_df['ID'] == 12]

,ID,Quartiere,Latitudine,Longitudine,Popolazione,Altitudine (m),Superficie (km2),Tipo Zona,Note
11,12,Villa Aurora,45.467,9.109,12150.0,142.0,3.1,Misto,terzo duplicato

In [23]:
new_df.loc[new_df['ID'] == 17, 'Quartiere'] = 'Collina degli Ulivi'
new_df.loc[new_df['ID'] == 17]

,ID,Quartiere,Latitudine,Longitudine,Popolazione,Altitudine (m),Superficie (km2),Tipo Zona,Note
16,17,Collina degli Ulivi,45.468,9.116,0.0,145.0,3.0,Residenziale,Popolazione forse errata

In [24]:
new_df.loc[new_df['ID'] == 6, 'Quartiere'] = 'Porto Argenteo'
new_df.loc[new_df['ID'] == 6]

,ID,Quartiere,Latitudine,Longitudine,Popolazione,Altitudine (m),Superficie (km2),Tipo Zona,Note
5,6,Porto Argenteo,45.4628,9.107,18100.0,135.0,2.3,Residenziale,duplicato (vedi ID 1)

In [25]:
new_df.loc[new_df['ID'] == 3, 'Quartiere'] = 'Borgo dei Fiori'
new_df.loc[new_df['ID'] == 3]

,ID,Quartiere,Latitudine,Longitudine,Popolazione,Altitudine (m),Superficie (km2),Tipo Zona,Note
2,3,Borgo dei Fiori,45.456,9.112,130.0,128.0,4.0,residenziale,presenza di scuole

In [26]:
new_df.loc[new_df['ID'] == 16, 'Quartiere'] = 'Prati Ventosi'
new_df.loc[new_df['ID'] == 16]

,ID,Quartiere,Latitudine,Longitudine,Popolazione,Altitudine (m),Superficie (km2),Tipo Zona,Note
15,16,Prati Ventosi,45.471,9.12,18300.0,138.0,3.8,Commerciale,simile a ID 15

In [27]:
new_df.loc[new_df['ID'] == 23, 'Quartiere'] = 'Riva delle Stelle'
new_df.loc[new_df['ID'] == 23]

,ID,Quartiere,Latitudine,Longitudine,Popolazione,Altitudine (m),Superficie (km2),Tipo Zona,Note
22,23,Riva delle Stelle,45.459,9.114,6100.0,110.0,3.4,Verde,varianti su Parco Est

In [28]:
new_df.loc[new_df['ID'] == 19, 'Quartiere'] = 'Borgo Antico Lido'
new_df.loc[new_df['ID'] == 19]

,ID,Quartiere,Latitudine,Longitudine,Popolazione,Altitudine (m),Superficie (km2),Tipo Zona,Note
18,19,Borgo Antico Lido,130.0,9.118,8250.0,202.0,5.5,rurale,maiuscole incoerenti

In [29]:
new_df.loc[new_df['ID'] == 15, 'Quartiere'] = 'Valle delle Rose'
new_df.loc[new_df['ID'] == 15]

,ID,Quartiere,Latitudine,Longitudine,Popolazione,Altitudine (m),Superficie (km2),Tipo Zona,Note
14,15,Valle delle Rose,45.471,9.12,18400.0,138.0,3.8,commerciale,zona fieristica

In [30]:
new_df.loc[new_df['ID'] == 30, 'Quartiere'] = 'Zona Est'
new_df.loc[new_df['ID'] == 30]

,ID,Quartiere,Latitudine,Longitudine,Popolazione,Altitudine (m),Superficie (km2),Tipo Zona,Note
29,30,Zona Est,45.46,9.111,10500.0,132.0,3.6,residenziale,nome scritto unito

In [32]:
new_df = new_df.drop('Note', axis=1)

In [33]:
new_df.to_csv('GeoInfo_Cittòvalle_pulito.csv', index=False)
new_df

,ID,Quartiere,Latitudine,Longitudine,Popolazione,Altitudine (m),Superficie (km2),Tipo Zona
0,1,Centro Storico,45.4628,9.1070,18230.0,135.0,2.3,residenziale
1,2,Borgo Nord,45.4670,9.1090,12000.0,142.0,3.1,misto
2,3,Borgo dei Fiori,45.4560,9.1120,130.0,128.0,4.0,residenziale
3,4,Colline Verdi,130.0000,9.1180,8300.0,200.0,5.5,rurale
4,5,Industriale,45.4700,9.1150,34000.0,130.0,130.0,industriale
5,6,Porto Argenteo,45.4628,9.1070,18100.0,135.0,2.3,Residenziale
6,7,Parco Est,45.4590,130.0000,5900.0,110.0,3.4,verde
7,8,borgo settentrionale,45.4670,9.1090,12200.0,142.0,3.1,MISTO
8,9,Zona sud-est,45.4559,9.1121,130.0,127.0,4.0,residenziale
10,11,ValleOvest,45.4632,9.1030,9200.0,121.0,2.9,Residenziale
11,12,Villa Aurora,45.4670,9.1090,12150.0,142.0,3.1,Misto
14,15,Valle delle Rose,45.4710,9.1200,18400.0,138.0,3.8,commerciale
15,16,Prati Ventosi,45.4710,9.1200,18300.0,138.0,3.8,Commerciale
16,17,Collina degli Ulivi,45.4680,9.1160,0.0,145.0,3.0,Residenziale
18,19,Borgo Antico Lido,130.0000,9.1180,8250.0,202.0,5.5,rurale
19,20,Nuova zona,45.4720,9.1220,15000.0,139.0,4.2,Residenziale
20,21,Vecchia zona,45.4400,9.0990,-200.0,125.0,3.3,Residenziale
21,22,Centro Antico,45.4628,9.1070,17900.0,135.0,2.3,residenziale
22,23,Riva delle Stelle,45.4590,9.1140,6100.0,110.0,3.4,Verde
23,24,Zona Sud,45.4530,9.1100,130.0,127.0,4.1,residenziale
24,25,Montealto,45.4800,9.1400,4300.0,260.0,6.5,rurale
25,26,zona expo,45.4710,9.1200,18500.0,138.0,3.8,commerciale
26,27,Villaggio Lago,45.4750,9.0990,7200.0,130.0,3.9,residenziale
27,28,Quartiere Luna,45.4680,9.1160,100.0,145.0,3.0,residenziale
28,29,Campagna Sud,45.4510,9.1000,3600.0,130.0,6.2,Rurale
29,30,Zona Est,45.4600,9.1110,10500.0,132.0,3.6,residenziale