In [42]:
import pandas as pd
import numpy as np

In [43]:
# Seria con indice automatico
persona = ['Giovanni', 'Valeria', 'Mario']

In [44]:
invitati = pd.Series(persona)
invitati

0    Giovanni
1     Valeria
2       Mario
dtype: object

In [45]:
# Serie con indice personalizzato
numeri = pd.Series([5,6,98,6,354])
numeri

0      5
1      6
2     98
3      6
4    354
dtype: int64

In [46]:
numeri = pd.Series([5,6,98,6,354], index=['a', 'b', 'c', 'd', 'e'])
numeri

a      5
b      6
c     98
d      6
e    354
dtype: int64

In [47]:
numeri_mist = pd.Series([5,6,98,6,354, 'franco'], index=['a', 'b', 'c', 'd', 'e', 'f'])
numeri_mist

a         5
b         6
c        98
d         6
e       354
f    franco
dtype: object

In [48]:
# Operazioni sulle series
numeri['b']

np.int64(6)

In [49]:
numeri + 5

a     10
b     11
c    103
d     11
e    359
dtype: int64

In [50]:
numeri * 5

a      25
b      30
c     490
d      30
e    1770
dtype: int64

In [51]:
numeri.mean()

np.float64(93.8)

In [52]:
numeri.max()

np.int64(354)

In [53]:
numeri.min()

np.int64(5)

In [54]:
tabella = {
    'Nome': ['Giovanni', 'Valeria', 'Marika'],
    'Eta': [38, 19, 29],
    'Citta': ['Napoli', 'Pescara', 'Chieti'],
    'Lavoro': ['Cuoco', np.nan, 'Segretaria']
}

In [55]:
df = pd.DataFrame(tabella)
df

       Nome  Eta    Citta      Lavoro
0  Giovanni   38   Napoli       Cuoco
1   Valeria   19  Pescara         NaN
2    Marika   29   Chieti  Segretaria

In [56]:
# Operazioni semplici
df['Nome']

0    Giovanni
1     Valeria
2      Marika
Name: Nome, dtype: object

In [57]:
df['Nome'][0] # Accedo prima alla colonna e poi alla riga!

'Giovanni'

In [58]:
df.iloc[0] # Restituisci la riga all'indice 0

Nome      Giovanni
Eta             38
Citta       Napoli
Lavoro       Cuoco
Name: 0, dtype: object

In [59]:
df.loc[1, 'Citta'] # Accesso alla cella specifica in modalita esplicita

'Pescara'

In [60]:
# Oerazione utile
df.describe() # Accesso alla statistiche

             Eta
count   3.000000
mean   28.666667
std     9.504385
min    19.000000
25%    24.000000
50%    29.000000
75%    33.500000
max    38.000000

In [ ]:
df.info() # Statistiche sui dati

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Nome    3 non-null      object
 1   Eta     3 non-null      int64
 2   Citta   3 non-null      object
 3   Lavoro  2 non-null      object
dtypes: int64(1), object(3)
memory usage: 228.0+ bytes

In [63]:
df['Eta'].mean()

np.float64(28.666666666666668)

In [66]:
df.head(1)

       Nome  Eta   Citta Lavoro
0  Giovanni   38  Napoli  Cuoco

In [65]:
df.tail(1)

     Nome  Eta   Citta      Lavoro
2  Marika   29  Chieti  Segretaria

In [67]:
# Filtri
df[df['Eta'] > 30]

       Nome  Eta   Citta Lavoro
0  Giovanni   38  Napoli  Cuoco

In [68]:
df[df['Citta'] == 'Chieti']

     Nome  Eta   Citta      Lavoro
2  Marika   29  Chieti  Segretaria

In [69]:
# Esportazione in CSV
df.to_csv('esportazione.csv', index=False)

In [70]:
df.to_csv('esportazioneIndice.csv', index=True)

In [71]:
# Leggere un CSV
df_csv = pd.read_csv('esportazione.csv')
df_csv

       Nome  Eta    Citta      Lavoro
0  Giovanni   38   Napoli       Cuoco
1   Valeria   19  Pescara         NaN
2    Marika   29   Chieti  Segretaria