## 1. sklearn.datasets: Caricamento e Generazione di Dataset

### Esercizio 1.1 (Base): Esplorazione Dataset Integrati
Carica il dataset Wine e analizza le sue caratteristiche principali.

In [1]:
# Esercizio 1.1: Carica il dataset Wine e rispondi alle seguenti domande:
# 1. Quanti campioni e feature contiene?
# 2. Quante classi ci sono?
# 3. Quali sono i nomi delle feature?
# 4. Visualizza le prime 3 righe dei dati

In [2]:
from sklearn.datasets import load_wine
import pandas as pd
from sklearn.datasets import make_classification
from sklearn.datasets import load_diabetes
from sklearn.datasets import make_regression
from sklearn.preprocessing import StandardScaler, MinMaxScaler
import numpy as np

In [3]:
try:
    wines = load_wine()
except:
    print("Errore nel caricamento del dataset")

In [4]:
df_wines = pd.DataFrame(wines.data, columns=wines.feature_names)
df_wines

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline
0,14.23,1.71,2.43,15.6,127.0,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065.0
1,13.20,1.78,2.14,11.2,100.0,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050.0
2,13.16,2.36,2.67,18.6,101.0,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185.0
3,14.37,1.95,2.50,16.8,113.0,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480.0
4,13.24,2.59,2.87,21.0,118.0,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,13.71,5.65,2.45,20.5,95.0,1.68,0.61,0.52,1.06,7.70,0.64,1.74,740.0
174,13.40,3.91,2.48,23.0,102.0,1.80,0.75,0.43,1.41,7.30,0.70,1.56,750.0
175,13.27,4.28,2.26,20.0,120.0,1.59,0.69,0.43,1.35,10.20,0.59,1.56,835.0
176,13.17,2.59,2.37,20.0,120.0,1.65,0.68,0.53,1.46,9.30,0.60,1.62,840.0
177,14.13,4.10,2.74,24.5,96.0,2.05,0.76,0.56,1.35,9.20,0.61,1.60,560.0

In [5]:
df_wines.describe()

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline
count,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000
mean,13.000618,2.336348,2.366517,19.494944,99.741573,2.295112,2.029270,0.361854,1.590899,5.058090,0.957449,2.611685,746.893258
std,0.811827,1.117146,0.274344,3.339564,14.282484,0.625851,0.998859,0.124453,0.572359,2.318286,0.228572,0.709990,314.907474
min,11.030000,0.740000,1.360000,10.600000,70.000000,0.980000,0.340000,0.130000,0.410000,1.280000,0.480000,1.270000,278.000000
25%,12.362500,1.602500,2.210000,17.200000,88.000000,1.742500,1.205000,0.270000,1.250000,3.220000,0.782500,1.937500,500.500000
50%,13.050000,1.865000,2.360000,19.500000,98.000000,2.355000,2.135000,0.340000,1.555000,4.690000,0.965000,2.780000,673.500000
75%,13.677500,3.082500,2.557500,21.500000,107.000000,2.800000,2.875000,0.437500,1.950000,6.200000,1.120000,3.170000,985.000000
max,14.830000,5.800000,3.230000,30.000000,162.000000,3.880000,5.080000,0.660000,3.580000,13.000000,1.710000,4.000000,1680.000000

In [6]:
n_campioni, n_feature = df_wines.shape
print(f"Numero di campioni (righe): {n_campioni}")
print(f"Numero di feature (colonne): {n_feature}")

Numero di campioni (righe): 178
Numero di feature (colonne): 13

In [7]:
print(df_wines.columns)

Index(['alcohol', 'malic_acid', 'ash', 'alcalinity_of_ash', 'magnesium',
       'total_phenols', 'flavanoids', 'nonflavanoid_phenols',
       'proanthocyanins', 'color_intensity', 'hue',
       'od280/od315_of_diluted_wines', 'proline'],
      dtype='object')

In [8]:
df_wines.head(3)

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline
0,14.23,1.71,2.43,15.6,127.0,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065.0
1,13.20,1.78,2.14,11.2,100.0,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050.0
2,13.16,2.36,2.67,18.6,101.0,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185.0

In [9]:
df_wines['target'] = wines.target
df_wines['target'].unique() 

print('Numero classi: ', len(df_wines['target'].unique()))

Numero classi:  3

### Esercizio 1.2 (Intermedio): Generazione Dataset Personalizzato
Crea un dataset sintetico per un problema di classificazione con specifiche caratteristiche.

In [10]:
# Esercizio 1.2: Genera un dataset di classificazione con:
# - 500 campioni
# - 8 feature totali (4 informative, 2 ridondanti)
# - 3 classi
# - 2 cluster per classe
# Poi visualizza le statistiche di base del dataset creato

In [11]:
X, y = make_classification(n_samples=500, n_features=8, n_informative=4, n_redundant=2, n_classes=3, n_clusters_per_class = 2, random_state=42)

print(f"\nShape del dataset: {X.shape}")
print(f"Numero di classi: {len(set(y))}")
print(f"Distribuzione delle classi: {list(y).count(0)} classe 0, {list(y).count(1)} classe 1")

Shape del dataset: (500, 8)
Numero di classi: 3
Distribuzione delle classi: 167 classe 0, 168 classe 1

### Esercizio 1.3 (Avanzato): Confronto Dataset Reali vs Sintetici
Confronta le caratteristiche del dataset Diabetes con un dataset sintetico di regressione.

In [12]:
# Esercizio 1.3: 
# 1. Carica il dataset Diabetes
# 2. Crea un dataset sintetico di regressione con le stesse dimensioni
# 3. Confronta le statistiche (media, std, range) delle feature

In [13]:
try:
    diabetes = load_diabetes()
except:
    print("Errore nel caricamento del dataset")

In [14]:
df_diabetes = pd.DataFrame(diabetes.data, columns = diabetes.feature_names)
df_diabetes

X_diabetes = diabetes.data
X_diabetes

array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990749, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06833155, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286131, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04688253,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452873, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00422151,  0.00306441]], shape=(442, 10))

In [15]:
df_diabetes.shape

(442, 10)

In [16]:
X, y = make_regression(n_samples=442, n_features=10, noise=0.2, random_state=42)



print(f"Media delle etichette: {X.mean():.2f}")
print(f"Deviazione standard delle etichette: {X.std():.2f}")
print(f"Range delle etichette: {(X.max() - X.min()):.2f}")

print(f"Media delle etichette (diabetes): {X_diabetes.mean():.2f}")
print(f"Deviazione standard delle etichette (diabetes): {X_diabetes.std():.2f}")
print(f"Range delle etichette (diabetes): {(X_diabetes.max() - X_diabetes.min()):.2f}")

Media delle etichette: 0.01
Deviazione standard delle etichette: 1.00
Range delle etichette: 7.17
Media delle etichette (diabetes): -0.00
Deviazione standard delle etichette (diabetes): 0.05
Range delle etichette (diabetes): 0.34

In [17]:
X_diabetes.shape, X.shape

((442, 10), (442, 10))

## 2. sklearn.preprocessing: Preprocessing dei Dati

### Esercizio 2.1 (Base): Scalatura Dati
Applica diverse tecniche di scalatura sui dati del Wine dataset.

In [18]:
# Esercizio 2.1: Applica StandardScaler e MinMaxScaler al dataset Wine
# Confronta i risultati mostrando media e deviazione standard prima e dopo

In [19]:
scaler = StandardScaler()
scaler_data = scaler.fit_transform(wines.data)

print(scaler_data)

print(f"Media delle etichette: {scaler_data.mean():.2f}")
print(f"Deviazione standard delle etichette: {scaler_data.std():.2f}")


X_2 = wines.data

print(f"Media delle etichette: {X_2.mean():.2f}")
print(f"Deviazione standard delle etichette: {X_2.std():.2f}")

[[ 1.51861254 -0.5622498   0.23205254 ...  0.36217728  1.84791957
   1.01300893]
 [ 0.24628963 -0.49941338 -0.82799632 ...  0.40605066  1.1134493
   0.96524152]
 [ 0.19687903  0.02123125  1.10933436 ...  0.31830389  0.78858745
   1.39514818]
 ...
 [ 0.33275817  1.74474449 -0.38935541 ... -1.61212515 -1.48544548
   0.28057537]
 [ 0.20923168  0.22769377  0.01273209 ... -1.56825176 -1.40069891
   0.29649784]
 [ 1.39508604  1.58316512  1.36520822 ... -1.52437837 -1.42894777
  -0.59516041]]
Media delle etichette: 0.00
Deviazione standard delle etichette: 1.00
Media delle etichette: 69.13
Deviazione standard delle etichette: 215.75

In [20]:
X_2.shape, scaler_data.shape

((178, 13), (178, 13))

In [21]:
min_max_scaler = MinMaxScaler()
normalized_data = min_max_scaler.fit_transform(X_2)

print(normalized_data)

print(f"Media delle etichette: {normalized_data.mean():.2f}")
print(f"Deviazione standard delle etichette: {normalized_data.std():.2f}")

[[0.84210526 0.1916996  0.57219251 ... 0.45528455 0.97069597 0.56134094]
 [0.57105263 0.2055336  0.4171123  ... 0.46341463 0.78021978 0.55064194]
 [0.56052632 0.3201581  0.70053476 ... 0.44715447 0.6959707  0.64693295]
 ...
 [0.58947368 0.69960474 0.48128342 ... 0.08943089 0.10622711 0.39728959]
 [0.56315789 0.36561265 0.54010695 ... 0.09756098 0.12820513 0.40085592]
 [0.81578947 0.66403162 0.73796791 ... 0.10569106 0.12087912 0.20114123]]
Media delle etichette: 0.41
Deviazione standard delle etichette: 0.22

### Esercizio 2.2 (Intermedio): Gestione Dati Mancanti
Crea e gestisci un dataset con valori mancanti usando diverse strategie di imputazione.

In [22]:
# Esercizio 2.2: 
# 1. Crea un array con valori mancanti (NaN) in posizioni casuali
# 2. Applica SimpleImputer con strategie: 'mean', 'median', 'most_frequent'
# 3. Confronta i risultati

In [23]:
X_new = np.random.randint(1, 10, size=(5, 5)).astype(float)

n_missing = 4
rows, cols = X_new.shape

nan_indices = set()
while len(nan_indices) < n_missing:
    i = np.random.randint(0, rows)
    j = np.random.randint(0, cols)
    nan_indices.add((i, j))

for i, j in nan_indices:
    X_new[i, j] = np.nan

X_new

array([[nan,  2.,  3.,  7.,  5.],
       [ 6., nan,  4.,  7.,  5.],
       [ 7.,  6.,  1., nan, nan],
       [ 1.,  1.,  3.,  4.,  7.],
       [ 2.,  7.,  6.,  2.,  1.]])

In [24]:
from sklearn.impute import SimpleImputer


imputer = SimpleImputer(strategy='mean')
imputed_data = imputer.fit_transform(X_new)

print(imputed_data)

[[4.  2.  3.  7.  5. ]
 [6.  4.  4.  7.  5. ]
 [7.  6.  1.  5.  4.5]
 [1.  1.  3.  4.  7. ]
 [2.  7.  6.  2.  1. ]]

In [25]:
imputer = SimpleImputer(strategy='median')
imputed_data = imputer.fit_transform(X_new)

print(imputed_data)

[[4.  2.  3.  7.  5. ]
 [6.  4.  4.  7.  5. ]
 [7.  6.  1.  5.5 5. ]
 [1.  1.  3.  4.  7. ]
 [2.  7.  6.  2.  1. ]]

In [26]:
imputer = SimpleImputer(strategy='most_frequent')
imputed_data = imputer.fit_transform(X_new)

print(imputed_data)

[[1. 2. 3. 7. 5.]
 [6. 1. 4. 7. 5.]
 [7. 6. 1. 7. 5.]
 [1. 1. 3. 4. 7.]
 [2. 7. 6. 2. 1.]]