Obiettivo: Analizzare un dataset di transazioni di un e-commerce per calcolare le metriche chiave come il valore medio degli ordini, le vendite totali per prodotto e il cliente più fedele.

Fasi Procedurali Suggerite
Caricamento e Preparazione delle Colonne:

Carica un dataset di transazioni (dovrebbe includere colonne come ID Transazione, ID Cliente, Data, Importo, Prodotto).

Assicurati che la colonna Data sia di tipo datetime (pd.to_datetime()).

Assicurati che la colonna Importo sia numerica.

Analisi Temporale:

Imposta la colonna Data come indice del DataFrame (.set_index()).

Calcola le vendite totali mensili utilizzando il metodo resample() con l'aggregazione sum().

Analisi per Prodotto:

Utilizza la funzione groupby() sulla colonna Prodotto.

Calcola:

Le vendite totali per ogni prodotto (.sum() sull'Importo).

Il numero di transazioni per ogni prodotto (.size() o .count()).

Analisi per Cliente:

Utilizza groupby() sulla colonna ID Cliente.

Calcola:

La spesa totale di ogni cliente.

Il numero di ordini effettuati da ogni cliente.

L'importo medio speso per ordine da ogni cliente.

Ordina il risultato per identificare il cliente con la spesa totale più alta (.sort_values()).

Unione di Dati (Opzionale):

Se hai un dataset separato con i dettagli anagrafici dei clienti (ID Cliente, Nome, Paese), unisci i due DataFrame utilizzando pd.merge() per aggiungere le informazioni anagrafiche al riepilogo delle spese.

In [1]:
import pandas as pd

df = pd.read_csv('E-commerce.csv')
df

    ID Transazione  ID Cliente        Data  Importo (€)            Prodotto
0                1         101  2025-01-15        45.60           Maglietta
1                2         102  2025-01-16        89.99              Scarpe
2                3         103  2025-01-17       120.00              Giacca
3                4         104  2025-01-18        15.00            Cappello
4                5         105  2025-01-19        55.50               Jeans
5                6         101  2025-01-20        35.00               Felpa
6                7         106  2025-01-21       250.00          Smartphone
7                8         107  2025-01-22        19.99             Calzini
8                9         108  2025-01-23        75.00            Orologio
9               10         109  2025-01-24        40.00               Zaino
10              11         110  2025-01-25        15.99             Sciarpa
11              12         111  2025-01-26       350.00              Tablet
12              13         112  2025-01-27        22.50             Cintura
13              14         113  2025-01-28       120.00     Scarpe da corsa
14              15         114  2025-01-29        75.50      Giacca a vento
15              16         115  2025-01-30        60.00           Pantaloni
16              17         116  2025-01-31        25.00              Guanti
17              18         117  2025-02-01        85.00  Scarpe da trekking
18              19         118  2025-02-02       100.00               Borsa
19              20         119  2025-02-03        10.00          Cappellino
20              21         120  2025-02-04        45.00           Maglietta
21              22         121  2025-02-05       140.00              Giacca
22              23         122  2025-02-06        90.00              Scarpe
23              24         123  2025-02-07        15.50             Calzini
24              25         124  2025-02-08        30.00               Felpa
25              26         125  2025-02-09        55.00               Jeans
26              27         126  2025-02-10        18.00             Sciarpa
27              28         127  2025-02-11       300.00              Laptop
28              29         128  2025-02-12        20.00             Cintura
29              30         129  2025-02-13        65.00      Giacca a vento
30              31         130  2025-02-14        50.00           Pantaloni
31              32         131  2025-02-15        27.00              Guanti
32              33         132  2025-02-16        80.00  Scarpe da trekking
33              34         133  2025-02-17        95.00               Borsa
34              35         134  2025-02-18        12.00          Cappellino

In [4]:
df.dtypes

ID Transazione      int64
ID Cliente          int64
Data               object
Importo (€)       float64
Prodotto           object
dtype: object

In [5]:
df['Data'].dtype

dtype('O')

In [7]:
df['Data'] = pd.to_datetime(df['Data'])
df['Data'].dtype

dtype('<M8[ns]')

In [6]:
df['Importo (€)'].dtype

dtype('float64')

In [10]:
df = df.set_index('Data')
df

            ID Transazione  ID Cliente  Importo (€)            Prodotto
Data
2025-01-15               1         101        45.60           Maglietta
2025-01-16               2         102        89.99              Scarpe
2025-01-17               3         103       120.00              Giacca
2025-01-18               4         104        15.00            Cappello
2025-01-19               5         105        55.50               Jeans
2025-01-20               6         101        35.00               Felpa
2025-01-21               7         106       250.00          Smartphone
2025-01-22               8         107        19.99             Calzini
2025-01-23               9         108        75.00            Orologio
2025-01-24              10         109        40.00               Zaino
2025-01-25              11         110        15.99             Sciarpa
2025-01-26              12         111       350.00              Tablet
2025-01-27              13         112        22.50             Cintura
2025-01-28              14         113       120.00     Scarpe da corsa
2025-01-29              15         114        75.50      Giacca a vento
2025-01-30              16         115        60.00           Pantaloni
2025-01-31              17         116        25.00              Guanti
2025-02-01              18         117        85.00  Scarpe da trekking
2025-02-02              19         118       100.00               Borsa
2025-02-03              20         119        10.00          Cappellino
2025-02-04              21         120        45.00           Maglietta
2025-02-05              22         121       140.00              Giacca
2025-02-06              23         122        90.00              Scarpe
2025-02-07              24         123        15.50             Calzini
2025-02-08              25         124        30.00               Felpa
2025-02-09              26         125        55.00               Jeans
2025-02-10              27         126        18.00             Sciarpa
2025-02-11              28         127       300.00              Laptop
2025-02-12              29         128        20.00             Cintura
2025-02-13              30         129        65.00      Giacca a vento
2025-02-14              31         130        50.00           Pantaloni
2025-02-15              32         131        27.00              Guanti
2025-02-16              33         132        80.00  Scarpe da trekking
2025-02-17              34         133        95.00               Borsa
2025-02-18              35         134        12.00          Cappellino

In [13]:
vendite = df['Importo (€)'].resample('M').sum()
vendite

C:\Users\Roman\AppData\Local\Temp\ipykernel_17304\4004609780.py:1: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  vendite = df['Importo (€)'].resample('M').sum()

Data
2025-01-31    1415.07
2025-02-28    1237.50
Freq: ME, Name: Importo (€), dtype: float64

In [17]:
vendite_pro = df.groupby('Prodotto')['Importo (€)'].sum()
vendite_pro

Prodotto
Borsa                 195.00
Calzini                35.49
Cappellino             22.00
Cappello               15.00
Cintura                42.50
Felpa                  65.00
Giacca                260.00
Giacca a vento        140.50
Guanti                 52.00
Jeans                 110.50
Laptop                300.00
Maglietta              90.60
Orologio               75.00
Pantaloni             110.00
Scarpe                179.99
Scarpe da corsa       120.00
Scarpe da trekking    165.00
Sciarpa                33.99
Smartphone            250.00
Tablet                350.00
Zaino                  40.00
Name: Importo (€), dtype: float64

In [20]:
transazioni_pro = df.groupby('Prodotto')['ID Transazione'].count()
transazioni_pro

Prodotto
Borsa                 2
Calzini               2
Cappellino            2
Cappello              1
Cintura               2
Felpa                 2
Giacca                2
Giacca a vento        2
Guanti                2
Jeans                 2
Laptop                1
Maglietta             2
Orologio              1
Pantaloni             2
Scarpe                2
Scarpe da corsa       1
Scarpe da trekking    2
Sciarpa               2
Smartphone            1
Tablet                1
Zaino                 1
Name: ID Transazione, dtype: int64

In [22]:
spesa_cliente = df.groupby('ID Cliente')['Importo (€)'].sum()
spesa_cliente

ID Cliente
101     80.60
102     89.99
103    120.00
104     15.00
105     55.50
106    250.00
107     19.99
108     75.00
109     40.00
110     15.99
111    350.00
112     22.50
113    120.00
114     75.50
115     60.00
116     25.00
117     85.00
118    100.00
119     10.00
120     45.00
121    140.00
122     90.00
123     15.50
124     30.00
125     55.00
126     18.00
127    300.00
128     20.00
129     65.00
130     50.00
131     27.00
132     80.00
133     95.00
134     12.00
Name: Importo (€), dtype: float64

In [24]:
ordini_cliente = df.groupby('ID Cliente')['ID Transazione'].count()
ordini_cliente

ID Cliente
101    2
102    1
103    1
104    1
105    1
106    1
107    1
108    1
109    1
110    1
111    1
112    1
113    1
114    1
115    1
116    1
117    1
118    1
119    1
120    1
121    1
122    1
123    1
124    1
125    1
126    1
127    1
128    1
129    1
130    1
131    1
132    1
133    1
134    1
Name: ID Transazione, dtype: int64

In [25]:
importo_cliente = df.groupby('ID Cliente')['Importo (€)'].mean()
importo_cliente

ID Cliente
101     40.30
102     89.99
103    120.00
104     15.00
105     55.50
106    250.00
107     19.99
108     75.00
109     40.00
110     15.99
111    350.00
112     22.50
113    120.00
114     75.50
115     60.00
116     25.00
117     85.00
118    100.00
119     10.00
120     45.00
121    140.00
122     90.00
123     15.50
124     30.00
125     55.00
126     18.00
127    300.00
128     20.00
129     65.00
130     50.00
131     27.00
132     80.00
133     95.00
134     12.00
Name: Importo (€), dtype: float64

In [29]:
spesa_alta = df.sort_values(by='Importo (€)', ascending=False)
spesa_alta

            ID Transazione  ID Cliente  Importo (€)            Prodotto
Data
2025-01-26              12         111       350.00              Tablet
2025-02-11              28         127       300.00              Laptop
2025-01-21               7         106       250.00          Smartphone
2025-02-05              22         121       140.00              Giacca
2025-01-28              14         113       120.00     Scarpe da corsa
2025-01-17               3         103       120.00              Giacca
2025-02-02              19         118       100.00               Borsa
2025-02-17              34         133        95.00               Borsa
2025-02-06              23         122        90.00              Scarpe
2025-01-16               2         102        89.99              Scarpe
2025-02-01              18         117        85.00  Scarpe da trekking
2025-02-16              33         132        80.00  Scarpe da trekking
2025-01-29              15         114        75.50      Giacca a vento
2025-01-23               9         108        75.00            Orologio
2025-02-13              30         129        65.00      Giacca a vento
2025-01-30              16         115        60.00           Pantaloni
2025-01-19               5         105        55.50               Jeans
2025-02-09              26         125        55.00               Jeans
2025-02-14              31         130        50.00           Pantaloni
2025-01-15               1         101        45.60           Maglietta
2025-02-04              21         120        45.00           Maglietta
2025-01-24              10         109        40.00               Zaino
2025-01-20               6         101        35.00               Felpa
2025-02-08              25         124        30.00               Felpa
2025-02-15              32         131        27.00              Guanti
2025-01-31              17         116        25.00              Guanti
2025-01-27              13         112        22.50             Cintura
2025-02-12              29         128        20.00             Cintura
2025-01-22               8         107        19.99             Calzini
2025-02-10              27         126        18.00             Sciarpa
2025-01-25              11         110        15.99             Sciarpa
2025-02-07              24         123        15.50             Calzini
2025-01-18               4         104        15.00            Cappello
2025-02-18              35         134        12.00          Cappellino
2025-02-03              20         119        10.00          Cappellino

In [30]:
df1 = pd.read_csv('Dati_Anagrafici.csv')
df1

    ID Cliente                Nome     Paese
0          101         Mario Rossi    Italia
1          102      Giulia Bianchi    Italia
2          103          Luca Verdi    Italia
3          104           Sara Neri    Italia
4          105     Francesco Gallo    Italia
5          106       Laura Fontana    Italia
6          107       Andrea Marino    Italia
7          108         Elisa Greco    Italia
8          109         Marco Conti    Italia
9          110       Chiara Romano    Italia
10         111       Giovanni Riva  Svizzera
11         112     Martina De Luca    Italia
12         113    Alessandro Serra   Francia
13         114         Paola Testa  Germania
14         115       Fabio Moretti    Italia
15         116         Sofia Rizzi    Italia
16         117      Matteo Colombo    Italia
17         118      Isabella Costa    Italia
18         119   Nicola De Angelis    Italia
19         120    Valentina Fabbri    Italia
20         121       Lorenzo Ferri    Italia
21         122     Alice Marchetti   Francia
22         123      Emanuele Gatti    Italia
23         124       Beatrice Sala    Italia
24         125       Tommaso Villa  Svizzera
25         126    Camilla Cattaneo    Italia
26         127     Simone Barbieri    Italia
27         128        Anna Rinaldi    Italia
28         129  Giovanni Battaglia    Italia
29         130      Irene Martelli    Italia
30         131        Davide Amato  Germania
31         132    Federica Sartori    Italia
32         133     Alberto Bianchi    Italia
33         134  Cristina De Santis    Italia

In [31]:
df_merge = pd.merge(df, df1)
df_merge

,ID Transazione,ID Cliente,Importo (€),Prodotto,Nome,Paese
0,1,101,45.60,Maglietta,Mario Rossi,Italia
1,2,102,89.99,Scarpe,Giulia Bianchi,Italia
2,3,103,120.00,Giacca,Luca Verdi,Italia
3,4,104,15.00,Cappello,Sara Neri,Italia
4,5,105,55.50,Jeans,Francesco Gallo,Italia
5,6,101,35.00,Felpa,Mario Rossi,Italia
6,7,106,250.00,Smartphone,Laura Fontana,Italia
7,8,107,19.99,Calzini,Andrea Marino,Italia
8,9,108,75.00,Orologio,Elisa Greco,Italia
9,10,109,40.00,Zaino,Marco Conti,Italia
10,11,110,15.99,Sciarpa,Chiara Romano,Italia
11,12,111,350.00,Tablet,Giovanni Riva,Svizzera
12,13,112,22.50,Cintura,Martina De Luca,Italia
13,14,113,120.00,Scarpe da corsa,Alessandro Serra,Francia
14,15,114,75.50,Giacca a vento,Paola Testa,Germania
15,16,115,60.00,Pantaloni,Fabio Moretti,Italia
16,17,116,25.00,Guanti,Sofia Rizzi,Italia
17,18,117,85.00,Scarpe da trekking,Matteo Colombo,Italia
18,19,118,100.00,Borsa,Isabella Costa,Italia
19,20,119,10.00,Cappellino,Nicola De Angelis,Italia
20,21,120,45.00,Maglietta,Valentina Fabbri,Italia
21,22,121,140.00,Giacca,Lorenzo Ferri,Italia
22,23,122,90.00,Scarpe,Alice Marchetti,Francia
23,24,123,15.50,Calzini,Emanuele Gatti,Italia
24,25,124,30.00,Felpa,Beatrice Sala,Italia
25,26,125,55.00,Jeans,Tommaso Villa,Svizzera
26,27,126,18.00,Sciarpa,Camilla Cattaneo,Italia
27,28,127,300.00,Laptop,Simone Barbieri,Italia
28,29,128,20.00,Cintura,Anna Rinaldi,Italia
29,30,129,65.00,Giacca a vento,Giovanni Battaglia,Italia
30,31,130,50.00,Pantaloni,Irene Martelli,Italia
31,32,131,27.00,Guanti,Davide Amato,Germania
32,33,132,80.00,Scarpe da trekking,Federica Sartori,Italia
33,34,133,95.00,Borsa,Alberto Bianchi,Italia
34,35,134,12.00,Cappellino,Cristina De Santis,Italia

In [32]:
df_merge.to_csv('E-commerce_nuovo.csv', index=False)