Progetto 5: Analisi Dati Semplice con Pandas e NumPy 📊
Questo progetto introduce l'uso di librerie esterne per l'analisi dei dati, come Pandas e NumPy, e include la gestione delle eccezioni.

Obiettivi:
Utilizzare NumPy per creare un array di numeri casuali che rappresentano temperature giornaliere.

Creare un DataFrame Pandas da questo array, aggiungendo una colonna per le date (usando il modulo datetime per generare una sequenza di date).

Aggiungere un'altra colonna al DataFrame che indichi se la temperatura è "Calda" (>25°C), "Moderata" (15-25°C) o "Fredda" (<15°C).

Calcolare la temperatura media, massima e minima del DataFrame.

Gestire le eccezioni:

Implementare un blocco try-except per gestire la ValueError se l'utente tenta di inserire un valore non numerico durante la creazione di un DataFrame manuale (anche se qui usiamo dati casuali, pensa a come lo faresti).

Gestire una ZeroDivisionError nel caso in cui un calcolo potesse portare a questo. (Potresti, ad esempio, simulare una divisione per zero in un blocco di test).

Generare un numero casuale usando il modulo random.

In [1]:
import numpy as np
import pandas as pd
from datetime import datetime, timedelta

In [2]:
tempo = np.random.randint(0,50, size=15)
tempo

array([32, 19, 39, 15, 14, 18,  7,  2, 16, 33, 10,  3, 17, 21, 47],
      dtype=int32)

In [3]:
# Data di inizio e fine
data_inizio = datetime(2025, 7, 1)
data_fine = datetime(2025, 7, 17)

# Generare la sequenza
sequenza_date = [data_inizio + timedelta(days=i) for i in range((data_fine - data_inizio).days + 1)]

# Stampare le date
for data in sequenza_date:
    print(data.strftime("%Y-%m-%d"))

2025-07-01
2025-07-02
2025-07-03
2025-07-04
2025-07-05
2025-07-06
2025-07-07
2025-07-08
2025-07-09
2025-07-10
2025-07-11
2025-07-12
2025-07-13
2025-07-14
2025-07-15
2025-07-16
2025-07-17

In [4]:
data = ['2025-07-01','2025-07-02','2025-07-03','2025-07-04',
        '2025-07-05','2025-07-06','2025-07-07','2025-07-08',
        '2025-07-09','2025-07-10','2025-07-11','2025-07-12',
        '2025-07-13','2025-07-14','2025-07-15']
data

['2025-07-01',
 '2025-07-02',
 '2025-07-03',
 '2025-07-04',
 '2025-07-05',
 '2025-07-06',
 '2025-07-07',
 '2025-07-08',
 '2025-07-09',
 '2025-07-10',
 '2025-07-11',
 '2025-07-12',
 '2025-07-13',
 '2025-07-14',
 '2025-07-15']

In [31]:
df = pd.DataFrame()
df['temperature'] = tempo
df

    temperature
0            32
1            19
2            39
3            15
4            14
5            18
6             7
7             2
8            16
9            33
10           10
11            3
12           17
13           21
14           47

In [32]:
df['date'] = data
df

    temperature        date
0            32  2025-07-01
1            19  2025-07-02
2            39  2025-07-03
3            15  2025-07-04
4            14  2025-07-05
5            18  2025-07-06
6             7  2025-07-07
7             2  2025-07-08
8            16  2025-07-09
9            33  2025-07-10
10           10  2025-07-11
11            3  2025-07-12
12           17  2025-07-13
13           21  2025-07-14
14           47  2025-07-15

In [33]:
percepire = ['caldo','moderato','fredda']

In [39]:
df

    temperature        date livello di calore
0            32  2025-07-01          moderato
1            19  2025-07-02          moderato
2            39  2025-07-03          moderato
3            15  2025-07-04          moderato
4            14  2025-07-05          moderato
5            18  2025-07-06          moderato
6             7  2025-07-07          moderato
7             2  2025-07-08          moderato
8            16  2025-07-09          moderato
9            33  2025-07-10          moderato
10           10  2025-07-11          moderato
11            3  2025-07-12          moderato
12           17  2025-07-13          moderato
13           21  2025-07-14          moderato
14           47  2025-07-15          moderato

In [49]:
def classifica_temperatura(temp):
    if temp > 25:
        return "Calda"
    elif 15 <= temp <= 25:
        return "Moderata"
    else: # temp < 15
        return "Fredda"
df['livello di calore'] = df['temperature'].apply(classifica_temperatura)
df

    temperature        date livello di calore
0            32  2025-07-01             Calda
1            19  2025-07-02          Moderata
2            39  2025-07-03             Calda
3            15  2025-07-04          Moderata
4            14  2025-07-05            Fredda
5            18  2025-07-06          Moderata
6             7  2025-07-07            Fredda
7             2  2025-07-08            Fredda
8            16  2025-07-09          Moderata
9            33  2025-07-10             Calda
10           10  2025-07-11            Fredda
11            3  2025-07-12            Fredda
12           17  2025-07-13          Moderata
13           21  2025-07-14          Moderata
14           47  2025-07-15             Calda

In [63]:
media = df['temperature'].mean()
print(f"Temperatura Media: {media:.2f}°C")

Temperatura Media: 19.53°C

In [64]:
massima = df['temperature'].max()
print(f"Temperatura Massima: {massima}°C")

Temperatura Massima: 47°C

In [65]:
minima = df['temperature'].min()
print(f"Temperatura Minima: {minima}°C")

Temperatura Minima: 2°C

In [61]:
import random
numero = random.randint(1, 10)
numero

6

In [62]:
print("\n--- Gestione Eccezioni: ZeroDivisionError ---")
denominatore = 0
try:
    risultato_divisione = 100 / denominatore
    print(f"Risultato della divisione: {risultato_divisione}")
except ZeroDivisionError:
    print("Errore: Impossibile dividere per zero!")
except Exception as e: # Cattura qualsiasi altra eccezione imprevista
    print(f"Si è verificato un errore inatteso: {e}")

--- Gestione Eccezioni: ZeroDivisionError ---
Errore: Impossibile dividere per zero!